#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6450130685                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your Shopping Lists, Notes, and Reminders—Right on Your Wrist! Keep all your essential info always visible on your Apple Watch. Watch the video to see it in action!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alexander Golikov                                
your_link                                 : https://www.linkedin.com/in/agolikov88/                     
#your_city                                 : Copenhagen                                
email_address                             : watchcardsfeedback@gmail.com
#facebook_username                         :                                           
#instagram_username                        : ebaehr
#twitter_username                          : ebaehr
github_username                           : agolikov88
#youtube_username                          :
#mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Reminders
    description                           : Reminders integration allows to import your reminders directly in the app and quickly set them as a new watch face.
    fontawesome_icon_name                 : bell
    
  - title                                 : Shopping Lists
    description                           : Ever found yourself juggling groceries while constantly pulling out your phone to check your shopping list? Now you can effortlessly put your list right on your wrist—keeping your hands free and your focus where it matters.
    fontawesome_icon_name                 : receipt

  - title                                 : Memo Cards
    description                           : Effortlessly create memo cards to master new skills or to keep essential information always at hand.
    fontawesome_icon_name                 : list

  - title                                 : Customization
    description                           : You can customize text position, fonts and backgrounds to make each of your watch cards unique.
    fontawesome_icon_name                 : toolbox

  - title                                 : Up to 24 Watch Cards per Watch Face
    description                           : With full version of the app you can add up to 24 separately customizable watch cards to each watch face.
    fontawesome_icon_name                 : layer-group

  - title                                 : Custom Watch Cards Backgrounds
    description                           : With full version of the app you can add custom backgrounds to your watch cards beyond what’s offered in the app by importing images from your photo library.
    fontawesome_icon_name                 : adjust

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 1.0
topbar_title_color                        : "#ffffff"

#cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#F1A33C"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#F1A33C"
feature_icons_background_color            : "#666666"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
